index/urls.py
from django.urls import path
from . import views


app_name = "index"


urlpatterns = [
    path("", views.index, name="home"),
    path("volunteer/", views.volunteer, name="volunteer"),
    path("messageboard/", views.messageboard, name="messageboard"),
    path('messageboard/<int:topic_id>/', views.topic, name='topic'), 
    path("contact/", views.contact, name="contact"),
    path("help/", views.help, name="help"),
    path("donate/", views.donate, name="donate"),
]

rcf_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('index.urls')),
    path('admin/', admin.site.urls),
]

index/models.py
from django.db import models


class Topic(models.Model):
    """
    Topic of post on message board.
    """
    title = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        """
        Returns a string representation of data.
        """
        return self.title


class Post(models.Model): 
    """
    Posts relating to its topic.
    """
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title= models.CharField(max_length=200)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        """
        Return a  string representing the post, shortened to 50 characters.
        """
        return f"{self.title[:50]}..."

index/views.py
from django.shortcuts import render
from.models import Topic


def index(request):
    """
    Shows the homepage of the RCF website.
    """
    page_title = "Home"
    return render(request, 'index.html', {'page_title': page_title})


def volunteer(request):
    """
    Shows the page of the RCF website on volunteer resources. 
    """
    page_title = "Volunteer Resources"
    return render(request, 'volunteer.html', {'page_title': page_title})


def help(request):
    """
    Shows the webpage on how to get involved with the RCF.
    """
    page_title = "How to Help"
    return render(request, 'help.html', {'page_title': page_title})

def donate(request):
    """
    Shows a page on how to donate to the RCF.
    """
    page_title = "Donation Guide"
    return render(request, 'donate.html', {'page_title': page_title})


def messageboard(request):
    """
    Shows the RCF forum.
    """
    page_title = "Forum"
    topics = Topic.objects.order_by('-date_added')
    context = {'page_title': page_title,
        'topics': topics}
    return render(request, 'messageboard.html', context)


def topic(request, topic_id): 
    """
    Show posts within a topic.
    """ 
    topic = Topic.objects.get(id=topic_id) 
    posts = topic.post_set.order_by('-date_posted')
    page_title = topic.title
    context = {'topic': topic, 'posts': posts, 'page_title': page_title} 
    return render(request, 'topic.html', context)


def contact(request):
    """
    Shows a page to contact RCF.
    """
    page_title = "Contact Us"
    return render(request, 'contact.html', {'page_title': page_title})

index/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 scalable=no">
    <title>{{page_title}} - Regina Community Fridge</title>
    {% load django_bootstrap5 %} 
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <style>
        .bg-med-green {
        background-color: forestgreen;
    
    }</style>
</head>
<body class="container-fluid">
    <nav class="navbar navbar-dark bg-med-green mb-4 border">
        <div class="container-fluid justify-content-center">
          <ul class="navbar-nav list-group-horizontal">
            <li class="nav-item text-nowrap mx-2"> <a class="nav-link text-white" href="{% url 'index:home' %}">Home</a></li>
            <li class="nav-item text-nowrap mx-2"><a class="nav-link text-white" href="{% url 'index:volunteer'%}">Volunteer</a></li>
            <li class="nav-item text-nowrap mx-2"><a class="nav-link text-white" href="{% url 'index:messageboard' %}">Forum</a></li>
            <li class="nav-item text-nowrap mx-2"><a class="nav-link text-white" href="{% url 'index:contact' %}">Contact Us</a></li>
          </ul>
        </div>
      </nav>
      <header class="mt-2 mb-2">
        {% block page_header %}
                <h1>{{ page_title }}</h1>
                {% endblock page_header %}
      </header>
      
        <main class="container-fluid mp-3">
            <div class="container-fluid mx-3">
                {%block content %}
                {%endblock content%}
            </div>
        
        </main>
</body>
</html>

index/templates/contact.html
{% extends "base.html" %}
{%load static%}


{%block page_header %}
<div class="p-3 mb-4 bg-light border rounded-3">
    <div class="container-fluid py-4">
    <h1>{{ page_title }}</h1>
    <p>We'd love to hear from you. If you would like to get in contact with the Regina Community Fridge, you may do so in the following ways:</p>
</div>
</div>
{%endblock page_header %}
{%block content %}
<div class="container-fluid text-center">
<h2>Email</h2>
<img src="{%static 'email.svg' %}" width="150" height="150" ald="A monochrome image of an envelope.">
<p class="text-break lh-lrg mx-5 my-5 px-5 py-5">the quickest and easiest way to contact us is through our email, <a href="reginacommunityfridge@gmail.com">reginacommunityfridge@gmail.com</a>. If you don't have an Instagram account, this is the way to reach us.</p>
<br>
<h2>Instagram</h2>
<img src="{%static 'instagram.svg' %}" width="150" height="150" alt="A monochrome image of the Instagram logo.">
<p class="text-break lh-lrg mx-5 my-5 px-5 py-5">If you have Instagram, you can also reach us via direct messaging (DM). We also post majority of our updates on Instagram, so it is the best way to keep up with us. we are <a href="https://www.instagram.com/reginacommunityfridge/">@reginacommunityfridge</a>.</p>
<br>
<h2>Facebook group</h2>
<img src="{%static 'facebook.svg' %}" width="150" height="150" alt="A monochrome image of the Facebook logo.">
<p class="text-break lh-lrg mx-5 my-5 px-5 py-5">Another way to get in contact with us is Facebook. You cannot message the people behind the community fridge directly here, but it is still a great source of information. Our group is called <a href="https://www.facebook.com/groups/314660200154441/">REGINA COMMUNITY FRIDGE (3037 Dewdney Ave)</a>.</p>
</div>
{% endblock content %}

index/templates/donate.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<div class="p-3 mb-4 bg-light border rounded-3"> 
    <div class="container-fluid py-4">
        <h1>{{ page_title }}</h1>
        <p>At Regina Community Fridge, the safety and well-being of our community is of extreme importance. For that reason, we have put together a donation guide in order to ensure everyone is on the same page.</p>
    </div>
</div>
{% endblock page_header %}
{% block content %}
<h2>Monetary donations </h2>
<p>Donating money to the Regina Community Fridge allows us to purchase more supplies to keep the fridge running. If you have a donation of this kind, you can <a href="https://www.gofundme.com/f/regina-community-fridge?utm_medium=copy_link&utm_source=customer&utm_campaign=p_na+share-sheet&rcid=8b99f1e11e6c45c1abec31c676eab74a">Donate to our GoFundMe</a></p>
<p>If you have a monetary donation in another form, <a href="{% url 'index:contact' %}">Feel free to reach out to us</a> and we will be in touch.</p>
<h2>Food</h2>
<h3>Do Donate</h3>
<ul>
    <li>Dairy and alternatives (milk, butter, yogurt, soy milk, coconut milk, margarine etc.)</li>
    <li>Fresh fruits and vegetables.</li>
    <li>Non-alcoholic drinks (water, juice, Gatorade, etc.)</li>
    <li>Frozen meals for the freezer. (Frozen pizza, TV dinners, bread, soup, etc.)</li>
    <li>Items that do not have to be frozen for the pantry (Canned goods, baby food, cereal, salt, sugar, oil, etc.)</li>
    <li>Single-serving snacks such as granola bars (If expiry date is visible on the product)</li>
    <li>Prepared meals if you are a business and/or have your food certification.</li>
    <p>Please note that all items must be sealed, and an expiration date must be visible.</p>
</ul>
<h3>Don't Donate</h3>
<ul>
    <li>Alcohol </li>
    <li>Home-cooked meals</li>
    <li>Rotten food</li>
    <li>Opened food.</li>
</ul>
<p>If you are a business and would like to make regular donations, <a href="{%url 'index:contact' %}">Get in touch.</a></p>
<h2>Non-food Items</h2>
<h3>Do Donate</h3>
<ul>
    <li>Pads and tampons</li>
    <li>Toothpaste, toothbrushes</li>
    <li>Soap, body wash, shampoo</li>
    <li>Hand sanitizer</li>
    <li>Medical masks</li>
    <h3>Don't Donate</h3>
    <li>Opened or used items</li>
</ul>
<h2>Pets</h2>
<h3>Do Donate</h3>
<ul>
<li>Unopened pet food</li>
</ul>
<h3>Don't Donate</h3>    
<ul>
    <li>Stale or opened pet food</li>
</ul>
{% endblock content %}

index/templates/help.html
{% extends "base.html" %}
{% load static %}


{% block page_header %}
<div class="p-3 mb-4 bg-light border rounded-3"> 
    <div class="container-fluid py-4">
        <h1>{{ page_title }}</h1>
        <p>There are a lot of ways to get involved with the Regina Community Fridge. Here is a short run-down of the main ways to get involved.</p>
    </div>
</div>
{% endblock page_header %}
{% block content %}
<div class="continer-fluid text-center">
        <h2>FlashFood pickups</h2>
        <img src="{% static 'flashfood.svg' %}" width="150" height="150" alt="A monochrome image of a shopping bag.">
        <p class="text-break lh-lrg mx-5 my-5 px-5 py-5">FlashFood is an app that allows grocery stores to post food that is at risk of going to waste. It is less expensive than if you were to buy it normally. Let us know when you are going to do a FlashFood pickup, and we will put a notice out to the <a href="{% url 'index:messageboard' %}">message board.</a></p>
        <p><a class="bg-light" href="https://apps.apple.com/ca/app/flashfood-grocery-deals/id1187314160">Download on Apple</a></p>
        <p><a class="bg-light" href="https://play.google.com/store/apps/details?id=com.flashfoodapp.android&hl=en_CA&gl=US">Download on Android</a></p>
        <br>

        <h2>Deliveries</h2>
        <img src="{%static 'driving.svg' %}" width="150" height="150" alt="A monochrome image of a car.">
        <p class="text-break lh-lrg mx-5 my-5 px-5 py-5">We get donations from donors that often end up going to waste due to the fact we do not have enough people to pick them up. As a result, we are always in need of drivers to bring them to the fridge.</p>
        <br>
        
        <h2>Kitchen team</h2>
        <img src="{% static 'kitchen.svg'%}" width="150" height="150" alt="A monochrome image of a kitchen stove and counter.">
        <p class="text-break lh-lrg mx-5 my-5 px-5 py-5">We have volunteers who come together to prepare meals that are safe and nutritious. In order for us to do this, we need to have multiple people interested. Just let us know if you are, and we will be in touch.</p>
        <br>


        <h2>Cleaning up</h2>
        <img src="{% static 'cleaning.svg'%}" width="150" height="150" alt="A monochrome image of a cleaning spray bottle.">
        <p class="text-break lh-lrg mx-5 my-5 px-5 py-5">Keeping the fridge a safe and sanitary place is a top priority. You can help us do so by cleaning up any debris or expired items in the fridge, or signing up for a regular cleaning shift.</p>
        <br>

    
        <h2>Donations</h2>
        <img src="{% static 'donate.svg'%}" width="150" height="150" alt="A monochrome image of staple food items, such as a big of what looks to be flour, an egg, and a milk jug.">
        <p class="text-break lh-lrg mx-5 my-5 px-5 py-5">We are always looking for food or monetary donations. See the donation guide for details on what is acceptable, and how to do so.</p>
        <br>

</div>
{% endblock content %}

index/templates/index.html
{% extends 'base.html' %}
{% load static %}
 
{% block page_header%}
<div class="p-3 mb-4 bg-light border rounded-3">
<div class="container-fluid text-center">
    <img src="{%static 'rcf_logo.png' %}" class="img-fluid">
<h1>Regina Community Fridge</h1>
<p>Take what you need, leave what you can.</p>
{% endblock page_header%}
</div>
</div>
{% block content %}
<h2>Our mission</h2>
<p><a href="https://globalnews.ca/news/10091223/saskatchewan-families-food-insecurity-statistics-canada/">According to Global News,</a> almost 20% of Saskatchewan experienced food insecurity in 2023, and that number is only growing. Our mission is to decrease that number by providing our community in Regina with a decentralized and easily accessible way to meet their basic human right of food.</p>
<h2>What we do</h2>
<p>We run a community fridge located in north central Regina. Here, you are free to take what you need at any time of day. All that we ask is that you help when you can. This can be something as simple as cleaning up boxes around the fridge or something as advanced as holding a large fundraiser. <br> To see all the ways you can help, <a href="{% url 'index:help' %}" class="fw-bold bg-light">click here.</a></p>
<h2>Visit us</h2>
<p>We are located at 3037 Dewdney Avenue near Regina Family Pharmacy. See below for a map.</p>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2540.261235705411!2d-104.62982641327179!3d50.45485990881123!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x531c1e6809b1e3f7%3A0x48cdd646e6eb37c9!2s3037%20Dewdney%20Ave%2C%20Regina%2C%20SK%20S4T%200Y3!5e0!3m2!1sen!2sca!4v1712080808973!5m2!1sen!2sca" width="300" height="225" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
{% endblock content %}

index/templates/messageboard.html
{% extends "base.html" %}
{%block page_header%}
<div class="p-3 mb-4 bg-light border rounded-3"> <div class="container-fluid py-4">
<h1>{{ page_title }}</h1>
<p>Connect with the Regina Community Fridge here.</p>
{%endblock page_header %}
</div>
</div>
{%block content %}
<h2>Topics</h2>
<ul>
{% for topic in topics %}
<li><a href="{% url 'index:topic' topic.id %}"> {{ topic.title }} </a></li>
{% empty %} <p>No messages.</p>
{% endfor %}
</ul>
{% endblock content %}

index/templates/topic.html
{% extends "base.html" %} 
{% block content %}
<a href="{% url 'index:messageboard' %}"> Back </a>
<h2>Posts</h2> <ul>
    {% for post in posts %}
    <h3>{{ post.title }}</h3>
    <p>{{ post.date_posted |date:'M d, Y H:i' }}</p>
        <p>{{ post.content|linebreaks }}</p> </li> 
        {% empty %} <li>There are no posts in this topic yet. <br>Check back later.</li>
        {% endfor %}
    </ul>
    {% endblock content %}

index/templates/volunteer.html
{% extends "base.html" %}
{% block page_header %}
<h1>{{ page_title }}</h1>
<p>Below, you will find a helpful list of volunteer resources.</p>
{% endblock page_header %}
{% block content %}
<h2>How to help</h2>
<p>A list of ways you can get involved with the Regina Community Fridge.</p>
<a href="{% url 'index:help' %}" class="fw-bold bg-light">View</a>
<h2>Donation Guide</h2>
<p>What and how you can donate to the fridge.</p>
<a href="{% url 'index:donate'  %}" class="fw-bold bg-light">View</a>
<h2>Contact us</h2>
<p>How you can get ahold of us. Please don't hesitate to email if you have questions.</p>
<a href="{% url 'index:contact'  %}" class="fw-bold bg-light">View</a>
{%endblock content%}